DROP TABLE IF EXISTS deployments;
DROP TABLE IF EXISTS jobs;
DROP TABLE IF EXISTS secret_refs;
DROP TABLE IF EXISTS skills;
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS users;
